DROP TABLE IF EXISTS items;
CREATE TABLE items (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	details TEXT NOT NULL,
	contact TEXT NOT NULL,
	category TEXT NOT NULL,
	price FLOAT(6) NOT NULL,
	pic TEXT NOT NULL
);
